/*
 * This Kotlin source file was generated by the Gradle 'init' task.
 */
package im.tony.project.app

import im.tony.project.utilities.StringUtils
import tornadofx.launch

fun main() {
    launch<TornadoApp>()
}
