/*
 * This file was generated by the Gradle 'init' task.
 */

plugins {
    id("im.tony.project.kotlin-library-conventions")
}

dependencies {
    api(project(":list"))
}

val compileKotlin: org.jetbrains.kotlin.gradle.tasks.KotlinCompile by tasks

compileKotlin.kotlinOptions {
  this.jvmTarget = "13"
  this.languageVersion = "1.4"
  this.apiVersion = "1.4"
}
