/*
 * This file was generated by the Gradle 'init' task.
 */

plugins {
  id("im.tony.project.kotlin-application-conventions")
  id("org.openjfx.javafxplugin") version "0.0.9"

  id("io.kotest") version "0.2.6"
  id("com.bnorm.power.kotlin-power-assert") version "0.6.1"
}

javafx {
  this.version = "15.0.1"
  this.modules(
    "javafx.controls",
    "javafx.graphics",
    "javafx.fxml",
    "javafx.media",
    "javafx.swing"
  )
}

dependencies {
  implementation(project(":utilities"))
  implementation(Deps.TornadoFx.Core)
  implementation(Deps.TornadoFx.ControlsFxExtensions)
  implementation(Deps.ScenicView)
  implementation(Deps.ControlsFX)
  implementation(Deps.FontAwesomeFxCommons)
  implementation(Deps.JfExtras.Controls)
  implementation(Deps.JfExtras.JMetro)
  implementation(Deps.JfExtras.GaugeLinear)
  implementation(Deps.JfExtras.Common)
  implementation(Deps.JfExtras.Menu)
  implementation(Deps.JfExtras.Fxml)
  implementation(Deps.JfExtras.Window)
  implementation(Deps.JfExtras.Agenda)
  implementation(Deps.JfExtras.Parent)
  implementation(Deps.JfExtras.iCalendarFx)
  implementation(Deps.Validation.Konform)
  implementation(Deps.Db.Sqlite)
  implementation(Deps.Exposed.Core)
  implementation(Deps.Exposed.Dao)
  implementation(Deps.Exposed.Jdbc)
  implementation(Deps.Faker)
  implementation(Deps.Logging.KotlinLogger.Lib)
  implementation(Deps.iKonli.Core)
  implementation(Deps.iKonli.JavaFx)
  implementation(Deps.iKonli.MaterialDesignPack)
  implementation(Deps.iKonli.DevkitIconsPack)

}

application {
  // Define the main class for the application.
  mainClass.set("im.tony.project.app.AppKt")
}

val compileKotlin: org.jetbrains.kotlin.gradle.tasks.KotlinCompile by tasks

compileKotlin.kotlinOptions {
  this.jvmTarget = "13"
  this.languageVersion = "1.4"
  this.apiVersion = "1.4"
}
