/*
 * This file was generated by the Gradle 'init' task.
 */

plugins {
  // Support convention plugins written in Kotlin. Convention plugins are build scripts in 'src/main' that automatically become available as plugins in the main build.
  `kotlin-dsl`
}

repositories {
  // Use the plugin portal to apply community plugins in convention plugins.
  gradlePluginPortal()
  mavenCentral()
  jcenter()
  maven(url = "https://dl.bintray.com/kotlin/kotlinx")
  maven(url = "https://oss.sonatype.org/content/repositories/snapshots/")
  maven(url = "https://dl.bintray.com/kotlin/kotlin-plugin/")
  maven(url = "https://kotlin.bintray.com/kotlin-dependencies")
  maven(url = "https://jetbrains.bintray.com/intellij-third-party-dependencies/")
}

dependencies {
  implementation("org.jetbrains.kotlin:kotlin-gradle-plugin")
}
